// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using YasminLetiereConfeitaria.Infrastructure.Context;

#nullable disable

namespace YasminLetiereConfeitaria.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260615055228_CorrigirPlaceholderImagens")]
    partial class CorrigirPlaceholderImagens
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("YasminLetiereConfeitaria.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Bolos decorados e com sabores inesquecíveis para celebrar.",
                            Icon = "cake",
                            Name = "Bolos Festivos",
                            Order = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Description = "Doces finos e tradicionais feitos com ingredientes nobres.",
                            Icon = "cookie",
                            Name = "Docinhos Gourmet",
                            Order = 2
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Description = "Sobremesas cremosas em camadas para adoçar qualquer dia.",
                            Icon = "local_bar",
                            Name = "Copos da Felicidade",
                            Order = 3
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Description = "Empadões caseiros, quiches e tortas salgadas para sua festa ou ceia.",
                            Icon = "restaurant",
                            Name = "Salgados",
                            Order = 4
                        });
                });

            modelBuilder.Entity("YasminLetiereConfeitaria.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("SeasonalTag")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-111111111111"),
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Massa vermelha aveludada com cacau premium, recheada com mousse cremoso à base de cream cheese e geleia artesanal de frutas vermelhas.",
                            ImageUrl = "/images/red_velvet.jpg",
                            IsAvailable = true,
                            Name = "Bolo Red Velvet Clássico",
                            Price = 160.00m,
                            UpdatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("a2222222-2222-2222-2222-222222222222"),
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Massa de chocolate nobre, recheio duplo de brigadeiro belga trufado gourmet e morangos frescos selecionados.",
                            ImageUrl = "/images/bolo_brigadeiro_duo.jpg",
                            IsAvailable = true,
                            Name = "Bolo Belga Trufado com Morango",
                            Price = 180.00m,
                            UpdatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("b1111111-1111-1111-1111-111111111111"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Description = "Brigadeiro super cremoso de pistache siciliano puro, envolto em pistache picado e finalizado com ganache.",
                            ImageUrl = "/images/pistachio_brigadeiro.jpg",
                            IsAvailable = true,
                            Name = "Brigadeiro de Pistache Siciliano",
                            Price = 6.50m,
                            UpdatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("a3333333-3333-3333-3333-333333333333"),
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Massa amanteigada premium com recheio de creme trufado, finamente espatulada em buttercream, decorada com fatias de laranja desidratada, morangos frescos e delicados ramos de eucalipto.",
                            ImageUrl = "/images/bolo_artesanal_laranja.jpg",
                            IsAvailable = true,
                            Name = "Bolo Espatulado Decorado",
                            Price = 240.00m,
                            UpdatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("b3333333-3333-3333-3333-333333333333"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Description = "Fatia generosa de bolo de cookie crocante por fora e macio por dentro, recheada com ganache cremosa de chocolate ao leite e Nutella premium.",
                            ImageUrl = "/images/cookie_cake.jpg",
                            IsAvailable = true,
                            Name = "Fatia de Cookie Cake Recheado",
                            Price = 16.00m,
                            UpdatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("a4444444-4444-4444-4444-444444444444"),
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Monte o seu bolo! Escolha o tamanho, recheio e adicionais. O valor é calculado na hora do pedido.",
                            ImageUrl = "/images/bolo_brigadeiro_duo.jpg",
                            IsAvailable = true,
                            Name = "Naked Cake Personalizado",
                            Price = 180.00m,
                            UpdatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("f1111111-1111-1111-1111-111111111111"),
                            CategoryId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Description = "Empadão tamanho família com massa levemente folhada que derrete na boca, super recheado com frango cremoso desfiado e requeijão.",
                            ImageUrl = "/images/empadao_frango.jpg",
                            IsAvailable = true,
                            Name = "Empadão Cremoso de Frango",
                            Price = 85.00m,
                            UpdatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("f2222222-2222-2222-2222-222222222222"),
                            CategoryId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Description = "Massa crocante e recheio cremoso à base de creme de leite fresco, alho-poró salteado na manteiga e cubos crocantes de bacon premium.",
                            ImageUrl = "/images/quiche_alho_poro.jpg",
                            IsAvailable = true,
                            Name = "Quiche de Alho Poró com Bacon",
                            Price = 95.00m,
                            UpdatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("d1111111-1111-1111-1111-111111111111"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Description = "Casca de chocolate ao leite recheada com camadas de brigadeiro de leite Ninho cremoso, pedaços de brownie úmido e brigadeiros gourmet.",
                            ImageUrl = "/images/easter_egg_brownie.jpg",
                            IsAvailable = true,
                            Name = "Ovo de Colher Brownie com Ninho",
                            Price = 85.00m,
                            SeasonalTag = "Páscoa",
                            UpdatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("d2222222-2222-2222-2222-222222222222"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Description = "Casca dupla de chocolate belga recheada com ganache trufada de pistache artesanal.",
                            ImageUrl = "/images/easter_egg_pistachio.jpg",
                            IsAvailable = true,
                            Name = "Ovo Trufado de Pistache",
                            Price = 110.00m,
                            SeasonalTag = "Páscoa",
                            UpdatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("e1111111-1111-1111-1111-111111111111"),
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Chocotone artesanal de fermentação natural, super recheado com brigadeiro de chocolate belga trufado e cobertura de chocolate meio amargo com granulados nobres.",
                            ImageUrl = "/images/christmas_chocotone.jpg",
                            IsAvailable = true,
                            Name = "Chocotone Trufado de Chocolate Belga",
                            Price = 95.00m,
                            SeasonalTag = "Natal",
                            UpdatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("f3333333-3333-3333-3333-333333333333"),
                            CategoryId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Description = "Folhado crocante artesanal recheado com lombo suíno assado desfiado, geleia suave de ameixa e queijo provolone. Perfeito para o Natal.",
                            ImageUrl = "/images/folhado_natal.jpg",
                            IsAvailable = true,
                            Name = "Folhado Festivo de Lombo com Ameixa",
                            Price = 110.00m,
                            SeasonalTag = "Natal",
                            UpdatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("YasminLetiereConfeitaria.Domain.Entities.Sazonalidade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Icone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MensagemExpirada")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Sazonalidades");

                    b.HasData(
                        new
                        {
                            Id = new Guid("51111111-1111-1111-1111-111111111111"),
                            Ativo = true,
                            AtualizadoEm = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataFim = new DateTime(2026, 4, 15, 23, 59, 59, 0, DateTimeKind.Utc),
                            DataInicio = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icone = "🐇",
                            MensagemExpirada = "As encomendas de Páscoa deste ano foram encerradas! Agradecemos imensamente o seu interesse. Quem sabe na próxima temporada?",
                            Nome = "Páscoa"
                        },
                        new
                        {
                            Id = new Guid("52222222-2222-2222-2222-222222222222"),
                            Ativo = true,
                            AtualizadoEm = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataFim = new DateTime(2026, 12, 25, 23, 59, 59, 0, DateTimeKind.Utc),
                            DataInicio = new DateTime(2026, 11, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icone = "🎄",
                            MensagemExpirada = "Nossas vagas para as encomendas de Natal já estão esgotadas! Boas Festas, nos vemos na próxima ceia!",
                            Nome = "Natal"
                        },
                        new
                        {
                            Id = new Guid("53333333-3333-3333-3333-333333333333"),
                            Ativo = true,
                            AtualizadoEm = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataFim = new DateTime(2026, 6, 12, 23, 59, 59, 0, DateTimeKind.Utc),
                            DataInicio = new DateTime(2026, 5, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icone = "💖",
                            MensagemExpirada = "Os pedidos para o Dia dos Namorados estão encerrados. Agradecemos a preferência, quem sabe no ano que vem?",
                            Nome = "Namorados"
                        },
                        new
                        {
                            Id = new Guid("54444444-4444-4444-4444-444444444444"),
                            Ativo = true,
                            AtualizadoEm = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataFim = new DateTime(2026, 6, 30, 23, 59, 59, 0, DateTimeKind.Utc),
                            DataInicio = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icone = "🌽",
                            MensagemExpirada = "Arraiá encerrado! As encomendas da Festa Junina já se encerraram. Que a festa continue no coração! Nos vemos no próximo arraiá. 🎉",
                            Nome = "Festa Junina"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Ativo = true,
                            AtualizadoEm = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataFim = new DateTime(2026, 5, 10, 23, 59, 59, 0, DateTimeKind.Utc),
                            DataInicio = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icone = "👩‍👦",
                            MensagemExpirada = "As encomendas do Dia das Mães foram encerradas. Obrigada pela preferência! Que todas as mães se sintam amadas e celebradas.",
                            Nome = "Dia das Mães"
                        },
                        new
                        {
                            Id = new Guid("56666666-6666-6666-6666-666666666666"),
                            Ativo = true,
                            AtualizadoEm = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataFim = new DateTime(2026, 10, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            DataInicio = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icone = "🎃",
                            MensagemExpirada = "As encomendas de Halloween foram encerradas! Esperamos ter adoçado o seu outubro. Até o próximo susto! 🎃",
                            Nome = "Halloween"
                        },
                        new
                        {
                            Id = new Guid("57777777-7777-7777-7777-777777777777"),
                            Ativo = true,
                            AtualizadoEm = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataFim = new DateTime(2026, 3, 3, 23, 59, 59, 0, DateTimeKind.Utc),
                            DataInicio = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icone = "🎭",
                            MensagemExpirada = "O carnaval acabou, mas os doces ficam! As encomendas de Carnaval já encerraram. Feliz Carnaval e até o próximo ano! 🎭",
                            Nome = "Carnaval"
                        },
                        new
                        {
                            Id = new Guid("58888888-8888-8888-8888-888888888888"),
                            Ativo = true,
                            AtualizadoEm = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataFim = new DateTime(2026, 8, 9, 23, 59, 59, 0, DateTimeKind.Utc),
                            DataInicio = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icone = "👨‍👦",
                            MensagemExpirada = "As encomendas do Dia dos Pais foram encerradas. Obrigada pela preferência! Que todos os pais se sintam especiais e celebrados.",
                            Nome = "Dia dos Pais"
                        },
                        new
                        {
                            Id = new Guid("59999999-9999-9999-9999-999999999999"),
                            Ativo = true,
                            AtualizadoEm = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataFim = new DateTime(2026, 10, 12, 23, 59, 59, 0, DateTimeKind.Utc),
                            DataInicio = new DateTime(2026, 9, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icone = "🎈",
                            MensagemExpirada = "As encomendas do Dia das Crianças foram encerradas! Que a alegria das crianças dure o ano todo. Até a próxima! 🎈",
                            Nome = "Dia das Crianças"
                        },
                        new
                        {
                            Id = new Guid("5aaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Ativo = true,
                            AtualizadoEm = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataFim = new DateTime(2027, 1, 2, 23, 59, 59, 0, DateTimeKind.Utc),
                            DataInicio = new DateTime(2026, 12, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icone = "🥂",
                            MensagemExpirada = "As encomendas de Réveillon foram encerradas! Que o Ano Novo seja cheio de doçura e realizações. Feliz 2027! 🥂",
                            Nome = "Réveillon"
                        },
                        new
                        {
                            Id = new Guid("5bbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Ativo = true,
                            AtualizadoEm = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataFim = new DateTime(2026, 3, 8, 23, 59, 59, 0, DateTimeKind.Utc),
                            DataInicio = new DateTime(2026, 2, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icone = "💐",
                            MensagemExpirada = "As encomendas do Dia da Mulher foram encerradas. Obrigada por celebrar conosco! Que todas as mulheres se sintam especiais todos os dias. 💐",
                            Nome = "Dia da Mulher"
                        });
                });

            modelBuilder.Entity("YasminLetiereConfeitaria.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            PasswordHash = "7501296317e7e875d8cbf01972c9cc279b993b4b1e04d342908a0ffbb1ab78cf",
                            Role = "Admin",
                            Username = "yasmin"
                        });
                });

            modelBuilder.Entity("YasminLetiereConfeitaria.Domain.Entities.Product", b =>
                {
                    b.HasOne("YasminLetiereConfeitaria.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("YasminLetiereConfeitaria.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
